version: '3'
services: 
  
  server:
    container_name: "api_products"
    build: .
    volumes:
      - ./:/node-app/
      - ./node_modules:/node-app/node_modules
    depends_on:
      - mongo
    links:
      - mongo
    ports:
      - '9000:9000'

  mongo: 
    container_name: mongo
    image: "mongo"
    ports: 
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/products_data
    environment:
      - MONGODB_ROOT_PASSWORD=password123

  
volumes:
  node_modules:  